/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./components/Layout/AppBar.vue')['default']
    AppSnackBar: typeof import('./components/Layout/AppSnackBar.vue')['default']
    AssistantTips: typeof import('./components/Warband/Assistant/AssistantTips.vue')['default']
    copy: typeof import('./components/Warband/Assistant/SelectSpells copy.vue')['default']
    CreateWizard: typeof import('./components/Warband/Assistant/CreateWizard.vue')['default']
    MiscIcon: typeof import('./components/MiscIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SchoolIcon: typeof import('./components/Warband/SchoolIcon.vue')['default']
    SelectItems: typeof import('./components/Warband/Assistant/SelectItems.vue')['default']
    'SelectItems.vue': typeof import('./components/Warband/Assistant/SelectItems.vue.vue')['default']
    SelectSoldiers: typeof import('./components/Warband/Assistant/SelectSoldiers.vue')['default']
    SelectSpells: typeof import('./components/Warband/Assistant/SelectSpells.vue')['default']
    TheCounter: typeof import('./components/TheCounter.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheInput: typeof import('./components/TheInput.vue')['default']
    WarbandEditor: typeof import('./components/Warband/WarbandEditor.vue')['default']
  }
}
